export const SET_FIELD = 'SET_FIELD'
export const SET_VALUE = 'SET_VALUE'
export const SET_VALUE_WITH_FIELD = 'SET_VALUE_WITH_FIELD'
export const RESET = 'RESET'
export const SET_META = 'SET_META'
export const REMOVE_FIELD = 'REMOVE_FIELD'
export const SET_VALUES = 'SET_VALUES'
